# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:13.5
    container_name: postgres
    hostname: postgres
    restart: always
    # env_file:
    #   - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cts
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: